version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: api_server
    command: node src/server.js
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  worker:
    build: .
    container_name: worker_service
    command: node src/workers/index.worker.js
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379